### ISSUE TITLE
Code Review feedback

### ISSUE THREAD

**Issue by mguy-usgs** [kallstadt-usgs/mLS#8]
Thought I would make one issue with multiple points of feedback. First, good readme, and I appreciated that the sample data was included too. Overall good, here is some feedback, most of it minor and around further documentation just for clarification:
- Error handling: any possible divide by zeros that should be  checked for or handled? Also, I don't know matlab but can functions throw errors that should be handled? Such as line 40, 42, 53, 71, etc.?
- I am for more inline code documentation when variable names are "idxm"
- how did you come up with 120 in lines 17 and 59? Should this be documented? Is it an assumption, or common limit, or?
- any relevant units ( e.g. meters, degrees) to add in documentation and code? Also are there any valid value ranges, such as greater than zero or between zero and 180, to add to code documentation?
- what version of matlab have you used/ tested this in? Good to note this in the documentation and/or code
- really good that you included example data. Can you define any expected units in the input and output? i don't have access to matlab so I cannot look at the data file, does it describe the data fields? are there any assumptions about precision or other data preparation or filtering?
-  The readme documentation mentions "the Northridge inventory" twice, is this common knowledge as to what this is? Is this the sample data? does the sample_data.mat file describe this?

**Comment by tanyashakan** [comment]
Thank you very much for the valuable comments. I have gone through the script. Here are my replies for your comments (they are given in the same order with your comments):

1- I have checked those lines for different inputs but  I didn't encounter any error. 
2- I am not clear about your comment here; do you suggest me to use another name for the variable "idxm".
3- I gave a short explanation for that (in line 48-49)
4- I gave some explanation about the input parameters including their units and ranges.
5- Matlab R2015b, I also noted that down in the script (in line 10).
6- I gave explanations regarding the units of inputs and output. The sample data is just an array with landslide sizes (meter square). It appears as the the required format of the script with a variable name of "Area".
7- Such details are explained in the corresponding paper. At the beginning of the  code I mentioned about the paper. When the paper will be ready to publish I will also give the entire citation for the paper.

**Comment by mguy-usgs** [comment]
regarding item #2, i was just commenting in general that many of the variable names are not very descriptive. for example, the variable name of idxm was not meaningful to me (e.g. idxm could be indexMidpoint), so making a general comment that more descriptive variable names can be helpful  to make the code more readable to a new-comer (anyone less familiar with the code)

**Comment by kallstadt-usgs** [comment]
Hakan addressed these so I am closing the issue.
